services:
  cache:
    image: redis:8.6.3-alpine
    restart: always
    ports:
      - '16340:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "mypass", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis:
    driver: local
